### ISSUE TITLE
review contents of this paper

### ISSUE THREAD

**Issue by 666-will** [clear-nus/NCDSSM#1]
Hi, I'm very excited about the emerge of this work. It makes sense that those traditional deep models all have high probability of converting themself from discrete to continuous form. However, it costs much time to deeply understand the paper without review on openreview.com. Could you provide the review to me? Thank you~

**Comment by abdulfatir** [comment]
Hi @666-will!

Thanks for your interest. Unfortunately, since the review process was confidential, I am not sure if I can reveal it publicly. That said, if you have any specific questions about the paper, I will be happy to answer them. You can also send me an email, if you prefer that.

**Comment by 666-will** [comment]
Thanks for your early reply, I would be ready for Q&A in several days : )

**Comment by 666-will** [comment]
So sorry for the delay of the issue.   
First issue is about the **ODE solver** which might be used in the code:
In **linear_step**(mu: Tensor...tn,h,method: str = "rk4",),  _h_ is the gap between each time step.
Does it mean we just smoothly modeling irregular time series by setting a common divisor--- _h_ ?

**Comment by 666-will** [comment]
The second is about **related work of NCDSSM**.
In the **pseudocode** of GRU-ODE -Bayes,  it simply apply GRU as a function to ODE-Solver, which called **continuously modelling** time series in that paper.  More recently, **Conti former** that is published in **nips2023** also has continuously model the irregular series.  
What is the differences between **GRU-ODE/conti former** and NCDSSM?

**Comment by abdulfatir** [comment]
> In linear_step(mu: Tensor...tn,h,method: str = "rk4",), h is the gap between each time step.

_h_ is the step size used for the [ODE solver](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods).

> What is the differences between GRU-ODE/conti former and NCDSSM?

We have briefly discussed this in the related work section. GRU-ODE-Bayes uses a _deterministic state_ which is updated via a Bayesian-inspired update step. In contrast, NCDSSM is an SSM with a _stochastic state_ driven by an SDE and uses a principled Bayesian update to incorporate new observations. I still need to check Contiformer in detail but it looks like they're proposing a transformer-based model for continuous-time modeling and are not using a state-space formulation with a stochastic state like NCDSSM.

**Comment by 666-will** [comment]
Thank you very much! Wish for your next amazing paper and have a good day : )

**Comment by abdulfatir** [comment]
Thanks! :)
